// This file is autogenerated. Changes will be overwritten.
#include "PRMOGMWJPH/moc_AudioProcessor.cpp"
#include "PRMOGMWJPH/moc_ClipboardManager.cpp"
#include "PRMOGMWJPH/moc_HotkeyManager.cpp"
#include "PRMOGMWJPH/moc_SpeechRecognizer.cpp"
#include "PRMOGMWJPH/moc_TextProcessor.cpp"
#include "MXUWEOXILK/moc_AudioVisualizer.cpp"
#include "MXUWEOXILK/moc_MainWindow.cpp"
#include "MXUWEOXILK/moc_SettingsDialog.cpp"
